# Generated by Django 2.0.5 on 2018-06-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180612_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='lytis',
            field=models.CharField(choices=[('v', 'Vyras'), ('m', 'Moteris'), ('p', 'Paslaptis')], default='p', max_length=1),
        ),
        migrations.AlterField(
            model_name='info',
            name='phone_number',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
