# Generated by Django 2.0.5 on 2018-06-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180612_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='phone_number',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
    ]
