# Generated by Django 2.0.5 on 2018-06-14 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_info_bookmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='last_read_messages',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='accounts.Comment'),
        ),
        migrations.AlterField(
            model_name='info',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, to='library.Book'),
        ),
    ]
