# Generated by Django 2.0.5 on 2018-11-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180614_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
