# Generated by Django 2.0.5 on 2018-11-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0013_auto_20181114_1502'),
        ('accounts', '0009_info_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='book_dislikes',
            field=models.ManyToManyField(blank=True, related_name='dislikes', to='library.Book'),
        ),
        migrations.AlterField(
            model_name='info',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='likes', to='library.Book'),
        ),
    ]
