# Generated by Django 2.0.5 on 2018-10-03 17:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('publisher', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('n', 'new'), ('c', 'closed'), ('s', 'successful'), ('o', 'open')], default='n', max_length=1)),
            ],
        ),
    ]
