# Generated by Django 2.0.5 on 2018-10-03 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0002_auto_20181003_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wish',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'wishes'},
        ),
        migrations.RemoveField(
            model_name='wish',
            name='description',
        ),
    ]
