# Generated by Django 2.0.5 on 2018-10-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0003_auto_20181003_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='description',
            field=models.TextField(default='testas'),
            preserve_default=False,
        ),
    ]
