# Generated by Django 2.0.5 on 2018-10-05 09:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0006_wish_writers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='opened_at',
        ),
        migrations.AddField(
            model_name='wish',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
