# Generated by Django 2.0.5 on 2018-10-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0007_auto_20181005_1220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wish',
            options={'ordering': ['-updated_at'], 'verbose_name_plural': 'wishes'},
        ),
        migrations.AddField(
            model_name='wish',
            name='admin_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
