# Generated by Django 2.0.5 on 2018-11-14 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0009_auto_20181007_1338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-refunded_at', '-created_at'], 'verbose_name_plural': 'Pervedimai'},
        ),
    ]
