# Generated by Django 2.0.5 on 2018-11-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0010_auto_20181114_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='book_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wish',
            name='isbn',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='wish',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='wish',
            name='publisher',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='wish',
            table='Prašymai',
        ),
    ]
