# Generated by Django 2.0.5 on 2018-11-26 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0011_auto_20181120_1423'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='wish',
            table='wishes',
        ),
    ]
