# Generated by Django 2.0.5 on 2018-12-13 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0012_auto_20181126_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wish',
            old_name='isbn',
            new_name='ISBN',
        ),
    ]
